name: Edge
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm ci

      - name: Build step
        run: |
          npm run build

      - name: Build PLUG.md
        run: |
          mv PLUG.md PLUG_SRC.md
          m4 PLUG_SRC.md > PLUG.md

      - name: Update release tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "edge"
          force_push_tag: true

      - name: Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: true
          tag_name: edge
          body: Automated build from commit ${{ github.sha }}
          files: |
            worker/silversearch.plug.js
            PLUG.md